SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 15
PLAYER_TURN_SPEED = 1000
PLAYER_SPEED = 400
PLAYER_SHOOT_SPEED = 699
PLAYER_SHOOT_COOLDOWN = 0.1

SHOT_RADIUS = 5
